# -*- coding: utf-8 -*-
"""CHAT BOT BRAMBANG AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoQDfy6C9fQTwHaAeh4tETf-EufOkFfS
"""

!pip install -q langchain
!pip install -q langchain-community
!pip install -q langchain-google-genai
!pip install -q faiss-cpu
!pip install -q unstructured

import langchain
import langchain_community
import langchain_google_genai
import faiss
import requests

print("✅ Semua package berhasil diimport!")

from google.colab import drive

drive.mount('/content/drive')

import os

print(os.listdir("/content/drive/MyDrive"))

import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    print(root)

from glob import glob
import os

KB_PATH = "/content/drive/MyDrive/BRAMBANG_AI/knowledge_base"

md_files = glob(os.path.join(KB_PATH, "**", "*.md"), recursive=True)

print(f"Jumlah file Markdown: {len(md_files)}\n")

for file in md_files:
    print(file)

from langchain_community.document_loaders import DirectoryLoader, TextLoader

loader = DirectoryLoader(
    KB_PATH,
    glob="**/*.md",
    loader_cls=TextLoader,
    loader_kwargs={"encoding": "utf-8"}
)

documents = loader.load()

print(f"Jumlah dokumen: {len(documents)}")

import langchain

print(langchain.__version__)

!pip install -q langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

import langchain
import langchain_google_genai

print("LangChain:", langchain.__version__)
print("Google GenAI:", langchain_google_genai.__version__)

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
    separators=[
        "\n# ",
        "\n## ",
        "\n### ",
        "\n\n",
        "\n",
        " "
    ]
)

chunks = text_splitter.split_documents(documents)

print("Jumlah Chunk :", len(chunks))

print(chunks[0].metadata)

print("="*80)

print(chunks[0].page_content)

print(chunks[10].metadata)

print("="*80)

print(chunks[10].page_content)

print(chunks[-1].metadata)

print("="*80)

print(chunks[-1].page_content)

from collections import Counter

sources = [c.metadata["source"].split("/")[-1] for c in chunks]

Counter(sources)

from google.colab import userdata
import os

os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")

from google import genai
from google.colab import userdata

client = genai.Client(
    api_key=userdata.get("GOOGLE_API_KEY")
)

response = client.models.generate_content(
    model="models/gemini-3.5-flash",
    contents="Halo, balas dengan kata BERHASIL"
)

print(response.text)

from langchain_google_genai import GoogleGenerativeAIEmbeddings

embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-2"
)

vector = embeddings.embed_query("Apa itu varietas Bauji?")

print("Dimensi embedding:", len(vector))
print(vector[:5])   # tampilkan 5 nilai pertama

!pip install -q google-genai

!pip install -U langchain-google-genai google-genai

!pip install -q sentence-transformers
!pip install -q langchain-huggingface

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="intfloat/multilingual-e5-base"
)

vector = embeddings.embed_query(
    "Apa itu varietas Bauji?"
)

print(len(vector))

print(len(chunks))

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(
    chunks,
    embeddings
)

print("Vector Database berhasil dibuat!")

vectorstore.save_local(
    "/content/drive/MyDrive/BRAMBANG_AI/faiss_index"
)

from langchain_community.vectorstores import FAISS

vectorstore = FAISS.load_local(
    "/content/drive/MyDrive/BRAMBANG_AI/faiss_index",
    embeddings,
    allow_dangerous_deserialization=True
)

print("✅ FAISS berhasil dimuat")

retriever = vectorstore.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 4,
        "fetch_k": 20,
        "lambda_mult": 0.7
    }
)

weather = get_weather()

print(weather)

from google import genai
from google.colab import userdata
import time

# ============================
# GEMINI CLIENT
# ============================

client = genai.Client(
    api_key=userdata.get("GOOGLE_API_KEY")
)

# ==========================================================
# WEATHER API
# ==========================================================

import requests

LATITUDE = -7.605
LONGITUDE = 111.903

def get_weather():

    url = "https://api.open-meteo.com/v1/forecast"

    params = {
        "latitude": LATITUDE,
        "longitude": LONGITUDE,
        "current": [
            "temperature_2m",
            "relative_humidity_2m",
            "precipitation",
            "rain",
            "wind_speed_10m"
        ]
    }

    response = requests.get(url, params=params)

    data = response.json()

    current = data["current"]

    weather_context = f"""
Cuaca Saat Ini

- Suhu : {current['temperature_2m']} °C
- Kelembaban : {current['relative_humidity_2m']} %
- Curah Hujan : {current['precipitation']} mm
- Hujan : {current['rain']} mm
- Kecepatan Angin : {current['wind_speed_10m']} km/jam
"""

    return weather_context

# ============================
# MEMORY CHAT
# ============================

chat_history = []

print("="*80)
print("🌱 Brambang AI Siap Digunakan")
print("Ketik 'exit' untuk keluar.")
print("="*80)

while True:

    query = input("\n👨‍🌾 Petani : ")

    if query.lower() == "exit":
        print("\n👋 Terima kasih telah menggunakan Brambang AI.")
        break

    # ===========================================
    # RETRIEVAL
    # ===========================================

    docs = retriever.invoke(query)

    context = "\n\n".join(
        doc.page_content
        for doc in docs
    )

    weather = get_weather()

    # ===========================================
    # CHAT HISTORY
    # ===========================================

    history = ""

    for user_msg, ai_msg in chat_history[-5:]:
        history += f"""
User : {user_msg}

Assistant : {ai_msg}

"""

    # ===========================================
    # PROMPT ENGINEERING
    # ===========================================
    prompt = f"""
# SYSTEM ROLE

Kamu adalah **Brambang AI**, asisten virtual khusus budidaya bawang merah Indonesia.

Tugasmu adalah membantu petani, penyuluh, mahasiswa, maupun masyarakat umum dengan memberikan informasi yang akurat, mudah dipahami, dan ramah.

Kamu berbicara seperti penyuluh pertanian yang berpengalaman, bukan seperti robot.

======================================================

# PERSONALITY

Selalu bersikap:

- Ramah
- Sopan
- Sabar
- Rendah hati
- Bersedia mengakui jika informasi belum lengkap
- Mengajak berdiskusi, bukan menggurui

Gunakan bahasa Indonesia yang alami seperti sedang berbicara langsung dengan petani.

Jangan terlalu formal.

======================================================

# OBJECTIVE

Jawablah pertanyaan pengguna menggunakan informasi pada Context.

Jika Context tidak cukup,
gunakan pengetahuan umum yang aman untuk membantu pengguna,
tetapi jelaskan bahwa informasi tersebut berasal dari pengetahuan umum,
bukan dari knowledge base.

======================================================

# CONVERSATION RULES

Jika pengguna:

• menyapa
→ balas dengan ramah.

Contoh:

"Halo Pak, ada yang bisa saya bantu mengenai budidaya bawang merah?"

------------------------------------------------------

Jika pengguna bercanda

Contoh:

"yeuu kocak"

jangan menjawab

"Informasi belum tersedia."

Balas secara santai.

Contoh:

"Haha 😄 semoga masih mau lanjut diskusi ya."

------------------------------------------------------

Jika pengguna membantah jawabanmu

Contoh

"Bukannya Bauji ya?"

Jangan defensif.

Akui bahwa kemungkinan memang terdapat beberapa sudut pandang.

Kemudian jelaskan mengapa jawabanmu berbeda berdasarkan Context.

Jika memang pengguna benar,
akui kesalahanmu dengan sopan.

------------------------------------------------------

Jika pengguna memberikan informasi baru

Contoh

"Saya membaca di Google bahwa..."

anggap itu sebagai bahan diskusi.

Jangan langsung mengatakan salah.

Bandingkan dengan Context.

======================================================

# CLARIFICATION RULES

Jika pertanyaan kurang jelas,
bertanyalah kembali.

Contoh

"Yang Bapak maksud musim tanam di Nganjuk atau daerah lain?"

atau

"Apakah yang dimaksud varietas untuk musim hujan atau musim kemarau?"

======================================================

# CONTEXT RULES

Prioritas jawaban:

1. Gunakan informasi dari Context.

2. Jika Context belum lengkap,
gunakan pengetahuan umum yang aman.

3. Jika benar-benar tidak mengetahui,
katakan dengan jujur.

JANGAN mengarang.

======================================================

# RESPONSE STYLE

Jawaban harus terasa alami.

Hindari kalimat seperti:

"Menurut Context..."

"Informasi belum tersedia."

"Sebagai AI..."

Gunakan kalimat seperti:

"Berdasarkan informasi yang saya miliki..."

"Dari data yang tersedia..."

"Untuk kondisi seperti itu..."

======================================================

# RESPONSE FORMAT

Jawaban:

<tuliskan jawaban>

Jika diperlukan, tambahkan:

Mengapa demikian?

<penjelasan>

Saran:

- poin 1
- poin 2
- poin 3

======================================================

# KNOWLEDGE BASE

{context}

======================================================

# WEATHER

{weather}

======================================================

# USER QUESTION

{query}

"""

    # ===========================================
    # GEMINI
    # ===========================================

    for retry in range(3):

        try:

            response = client.models.generate_content(
                model="models/gemini-3.5-flash",
                contents=prompt
            )

            answer = response.text

            print("\n🤖 Brambang AI\n")
            print(answer)
            print("="*80)

            chat_history.append(
                (query, answer)
            )

            break

        except Exception as e:

            if retry < 2:

                print("\n⏳ Server sibuk, mencoba lagi...")
                time.sleep(3)

            else:

                print(e)

